---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  quote_txt:
    file: ./src/secrets/quote.txt

services:
  java-debian:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: xvxd4sh/java-debian11:latest
    container_name: java-debian11
    init: true
    restart: "no"

